[package]
name = "fin-lib"
version = "0.2.0"
authors = ["Zahari Petkov <zahari@balena.io>"]
description = "balenaFin base library"
license = "Apache-2.0"
edition = "2018"

[dependencies]
nix = "0.18"
libc = "0.2"
